name: "PROJECTO - MISO: SOFTWARE CLOUD G32"
aws:
  AWS_ACCESS_KEY_ID: ASIA3GGSDDLFENY4TYJJ
  AWS_SECRET_ACCESS_KEY: pjIW+UJleLro8QzJi1U5EYOtTJwBAnoMSmMAURFI
  AWS_SESSION_TOKEN: FwoGZXIvYXdzEJX//////////wEaDC8/gPWCWWUvai9qnyLLAdZ9/g5teJvN1Z1nXLOKJdRpfNi9lC72+m4nTFO+s1QJw50iZgNHUu+e/RYmOi8Ugnz+noYb/7UIY6v0p7Wu6e+nMeNOKL0WB+OsGNxK85wFP4cDNgp1xDmD83Ea2YrhS2TJMwQCfCLHMsu3vb8t0Iod6QOdjUiFW00DzxcTkDWKOQwkB0WajkCd/ZU45rwca/iAxeD+z/4pUZHBl6Th6qy8WRCx9JFCCM5XBEJIuKvhwDkcxYRy86Q7+Q4+9a3LUAcfPDzuyx0rbxebKP6jrY0GMi2FStQUh2MCMXA8qlv2Ak9tfzJAeWQOeAQK+ARHzWX7XQ/OWaDlDJNOOgwsdVE=
  UPLOAD_FOLDER: uploaded_files
  DOWNLOAD_FOLDER: processed_files
  MAX_CONTENT_LENGTH: 40000000
  BUCKET_NAME: "miso-cloud-gr32"
  SECRET_KEY: "xD$F*CV&O0cU"
  SQS_QUEUE_NAME: conversor_queue
smtp:
  SERVER: "172.168.1.252"
  PORT: 1025
  EMAIL: "conversor_miso@conversor.com"
  